/*
 * Copyright 2013 shizihu.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.xuyun.tools;

import com.github.xuyun.tools.ui.userid.UserIDFrame;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author shizihu
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgAbout = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jlblCodePath = new javax.swing.JLabel();
        btnUserID = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        mitmCode = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mitmExit = new javax.swing.JMenuItem();

        dlgAbout.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgAbout.setTitle("系统信息");
        dlgAbout.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 1, 14)); // NOI18N
        jLabel1.setText("系统源代码：");
        dlgAbout.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jlblCodePath.setText("http://");
        dlgAbout.getContentPane().add(jlblCodePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 370, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("工具集");
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(2, 2, 20, 20));

        btnUserID.setText("UserID分割器");
        btnUserID.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUserID.setMaximumSize(new java.awt.Dimension(120, 80));
        btnUserID.setMinimumSize(new java.awt.Dimension(120, 80));
        btnUserID.setPreferredSize(new java.awt.Dimension(120, 80));
        btnUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserIDActionPerformed(evt);
            }
        });
        getContentPane().add(btnUserID);

        jButton2.setText("开发中...");
        jButton2.setEnabled(false);
        jButton2.setMaximumSize(new java.awt.Dimension(120, 80));
        jButton2.setMinimumSize(new java.awt.Dimension(120, 80));
        jButton2.setPreferredSize(new java.awt.Dimension(120, 80));
        getContentPane().add(jButton2);

        jButton7.setText("开发中...");
        jButton7.setEnabled(false);
        jButton7.setMaximumSize(new java.awt.Dimension(120, 80));
        jButton7.setMinimumSize(new java.awt.Dimension(120, 80));
        jButton7.setPreferredSize(new java.awt.Dimension(120, 80));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);

        jButton3.setText("开发中...");
        jButton3.setEnabled(false);
        jButton3.setMaximumSize(new java.awt.Dimension(120, 80));
        jButton3.setMinimumSize(new java.awt.Dimension(120, 80));
        jButton3.setPreferredSize(new java.awt.Dimension(120, 80));
        getContentPane().add(jButton3);

        menuFile.setText("文件");

        mitmCode.setText("源代码");
        mitmCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitmCodeActionPerformed(evt);
            }
        });
        menuFile.add(mitmCode);
        menuFile.add(jSeparator1);

        mitmExit.setText("退出");
        mitmExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitmExitActionPerformed(evt);
            }
        });
        menuFile.add(mitmExit);

        menuBar.add(menuFile);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserIDActionPerformed
        // TODO add your handling code here:
        JFrame frame = new UserIDFrame();
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }//GEN-LAST:event_btnUserIDActionPerformed

    private void mitmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitmExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_mitmExitActionPerformed

    private void mitmCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitmCodeActionPerformed
        String src = "https://github.com/obullxl/xuyun-tools";
        this.jlblCodePath.setText(src);
        
        this.dlgAbout.setSize(350, 150);
        this.dlgAbout.setLocationRelativeTo(this);
        this.dlgAbout.setVisible(true);
    }//GEN-LAST:event_mitmCodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
            // ignore
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame mui = new MainUI();
                mui.setLocationRelativeTo(null);
                mui.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUserID;
    private javax.swing.JDialog dlgAbout;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel jlblCodePath;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem mitmCode;
    private javax.swing.JMenuItem mitmExit;
    // End of variables declaration//GEN-END:variables
}
